.PHONY: clean All

All:
	@echo "----------Building project:[ helpers - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/projects/linux/codelite" && "$(MAKE)" -f  "helpers.mk"
	@echo "----------Building project:[ lua_shared - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/projects/linux/codelite" && "$(MAKE)" -f  "lua_shared.mk"
	@echo "----------Building project:[ scanning - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/scanning/projects/linux/codelite" && "$(MAKE)" -f  "scanning.mk"
	@echo "----------Building project:[ detouring - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/detouring/projects/linux/codelite" && "$(MAKE)" -f  "detouring.mk"
	@echo "----------Building project:[ minhook - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/detouring/projects/linux/codelite" && "$(MAKE)" -f  "minhook.mk"
	@echo "----------Building project:[ hde - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/detouring/projects/linux/codelite" && "$(MAKE)" -f  "hde.mk"
	@echo "----------Building project:[ tier1 - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/sourcesdk-minimal/projects/linux/codelite" && "$(MAKE)" -f  "tier1.mk"
	@echo "----------Building project:[ LZMA - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/sourcesdk-minimal/projects/linux/codelite" && "$(MAKE)" -f  "LZMA.mk"
	@echo "----------Building project:[ gmsv_writetocfg - Release ]----------"
	@"$(MAKE)" -f  "gmsv_writetocfg.mk"
clean:
	@echo "----------Cleaning project:[ helpers - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/projects/linux/codelite" && "$(MAKE)" -f  "helpers.mk"  clean
	@echo "----------Cleaning project:[ lua_shared - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/projects/linux/codelite" && "$(MAKE)" -f  "lua_shared.mk"  clean
	@echo "----------Cleaning project:[ scanning - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/scanning/projects/linux/codelite" && "$(MAKE)" -f  "scanning.mk"  clean
	@echo "----------Cleaning project:[ detouring - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/detouring/projects/linux/codelite" && "$(MAKE)" -f  "detouring.mk"  clean
	@echo "----------Cleaning project:[ minhook - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/detouring/projects/linux/codelite" && "$(MAKE)" -f  "minhook.mk"  clean
	@echo "----------Cleaning project:[ hde - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/detouring/projects/linux/codelite" && "$(MAKE)" -f  "hde.mk"  clean
	@echo "----------Cleaning project:[ tier1 - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/sourcesdk-minimal/projects/linux/codelite" && "$(MAKE)" -f  "tier1.mk"  clean
	@echo "----------Cleaning project:[ LZMA - Release ]----------"
	@cd "/mnt/c/Users/fopses/Desktop/TheGmodThing/garrysmod_common/sourcesdk-minimal/projects/linux/codelite" && "$(MAKE)" -f  "LZMA.mk"  clean
	@echo "----------Cleaning project:[ gmsv_writetocfg - Release ]----------"
	@"$(MAKE)" -f  "gmsv_writetocfg.mk" clean
